phrase:
  access_token: d475a2993b43427d6da025629f8dd56bd7bade85ddc92e538e36ed6237f4bac7 #Add your personal access token to authenticate, you can find the steps on how to create one here: https://help.phrase.com/help/access-tokens
  file_format: csv

    push:
    sources:
    # Demo1
    - file: ./en.csv
      project_id: "0fbdcc518e6a2d9aa5ba037d4833bf9f"

      params:
        locale_id: "d0183a8917c19f8bd71daf354aae0ba9"
        update_translations: true

      locale_mapping:
        en: 2

      format_options:
          key_index: 1
          tag_column: 3

    # Demo2
    - file: ./en.csv
      project_id: "4d74f1ecb61ae818c00b2082774c4c48"
      params:
        locale_id: "f942eea30bc9611ef20570c65e022cae"
        update_translations: true

          locale_mapping:
            en: 2

          format_options:
              key_index: 1
              tag_column: 3


  # Demo3
  - file: ./en.csv
    project_id: "1a3075810d1d464dc17d5bdde35aaac2"
    params:
      locale_id: "b300e53839060171e65d8ab2a6c91be9"
      update_translations: true

        locale_mapping:
          en: 2

        format_options:
          key_index: 1
          tag_column: 3



  # Demo4
  - file: ./en.csv
    project_id: "18aeb06f40d919d0f3d97e5d5714b770"
    params:
      locale_id: "5bab446b00bf11f463a85be27d43a5df"
      file_format: csv
      update_translations: true

  locale_mapping:
    en: 2

  format_options:
    key_index: 1
    tag_column: 3



  pull:
    targets:
    # Demo1
    - file: ./en.csv
      project_id: "0fbdcc518e6a2d9aa5ba037d4833bf9f"
        format_options:
            export_tags: true

    # Demo2
    - file: ./en.csv
      project_id: "4d74f1ecb61ae818c00b2082774c4c48"
        format_options:
            export_tags: true

        # Demo3
        - file: ./en.csv
          project_id: "1a3075810d1d464dc17d5bdde35aaac2"
            format_options:
                export_tags: true

            # Demo4
            - file: ./en.csv
              project_id: "18aeb06f40d919d0f3d97e5d5714b770"
                format_options:
                    export_tags: true
